Honeycomb workshop
brown-ccv/ccv-website-content pull request #133
Opened 2022-09-06 18:59 UTC by RobertGemmaJr

Adds a file for the Honeycomb demo workshop and Ben Heasly's workshop on jsPysch. Not sure if Ben's workshop is relevant to our workshops? Happy to delete if we don't think it should end up on the website

2022-09-06 21:19 UTC, mirestrepo requested changes

2022-09-06 21:19 UTC, mirestrepo commented on our-work/workshops-and-talks/honeycomb.yml
> +description: Step by step guide on creating a new honeycomb repository. The first video covers installing dependencies and basic git workflows, and the second covers Firebase set up. Workshop was hel
```suggestion
description: Step by step guide on creating new behavioral/psychophysiological tasks for clinic, laboratory, and home using a template repository called [Honeycomb](https://brown-ccv.github.io/honeycomb-docs/docs/), which CCV has developed in collaboration with the Borton, Frank and Nassar labs. The first video covers installing dependencies and basic git workflows, and the second covers Firebase set up. Workshop was held on August 10, 2022. The third video corresponds to a follow up workshop organized by the Nassar lab and lead by Ben Heasly on **Converting a jsPsych task with Honeycomb**
```

2022-09-06 21:19 UTC, mirestrepo commented on our-work/workshops-and-talks/honeycomb.yml
> +    url: https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5903a4db-9759-4cef-a9e8-aefd014adaa5
```suggestion
    url: https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5903a4db-9759-4cef-a9e8-aefd014adaa5
  - category: video 
     url: https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=096759c6-7d5b-4ead-b307-aefc01539396
```

2022-09-06 21:19 UTC, mirestrepo commented on our-work/workshops-and-talks/jsPsych.yml
> +groups:
This group doesn't make sense to me.... If it can be empty, lets leave it empty. I'd like to remove that, but I'll need to consult more

2022-09-07 18:04 UTC, eldu requested changes
Can you add in the slides too?

https://docs.google.com/document/d/1pk8-E1NpbIrjTmWZBVPsmusAl_NEMXy8XE5FdamXx08/edit?usp=sharing

2022-09-07 18:34 UTC, RobertGemmaJr commented
> Can you add in the slides too?

Done! How are the share settings set up? Will anyone be able to see the slides if they click the link on the website?

2022-09-07 21:30 UTC, mirestrepo commented
> > Can you add in the slides too?
> 
> Done! How are the share settings set up? Will anyone be able to see the slides if they click the link on the website?

Seems okay
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1238840/188985240-f639dc06-b5da-480c-a9f3-61cfaeb4eed3.png">

2022-09-07 21:33 UTC, mirestrepo requested changes
It think its close, but the markdown is not showing up as intended

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1238840/188985840-049a6689-4742-4a4f-8cd9-5613c5a00736.png">

The links and bold is not working. We may need direct html tags for that. Can you try a couple of things there?

2022-09-09 14:32 UTC, RobertGemmaJr commented
Looks like the description can only be text... should I add another link or leave it be?

![image](https://user-images.githubusercontent.com/38439940/189374444-7915329f-2bb4-40d8-bedd-7e23c942212d.png)

2022-09-12 14:45 UTC, eldu commented
> Looks like the description can only be text... should I add another link or leave it be?
> 
> ![image](https://user-images.githubusercontent.com/38439940/189374444-7915329f-2bb4-40d8-bedd-7e23c942212d.png)

@RobertGemmaJr Yeah, another link sounds good then

2022-09-12 15:15 UTC, RobertGemmaJr commented
Should be all set now!

2022-09-12 18:04 UTC, eldu approved these changes
🚢

2022-09-12 18:05 UTC, mirestrepo approved these changes
🚀

2022-09-12 19:05 UTC, merged