feat: add biomed to collaborations
brown-ccv/ccv-website-content pull request #197
Opened 2023-07-06 19:12 UTC by tdivoll

This PR adds the Biomed diversity survey collaboration to the list of collaborations!

2023-07-07 21:44 UTC, hollandjg requested changes
just one minor issue – it's that tab again.

2023-07-07 21:44 UTC, hollandjg commented on schemas/collaborations.yml
> +	        'acadia',
```suggestion
          'acadia',
```

2023-07-07 21:44 UTC, hollandjg commented on schemas/collaborations.yml
> +	        'acadia',
looks like there's an out of place tab here

2023-07-19 16:58 UTC, eldu approved these changes

2023-07-20 15:47 UTC, hollandjg approved these changes
🚀 Sorry! I Ignored the re-review notification here!

2023-07-20 17:39 UTC, merged