Adding  Camilo's bio to people.yml
brown-ccv/ccv-website-content pull request #212
Opened 2023-09-07 18:49 UTC by kmilo9999

Just a brief description on who I am.

2023-09-12 20:09 UTC, eldu requested changes
Just some spelling and punctuation updates ! Looks good !

2023-09-12 20:09 UTC, eldu commented on about/people.yml
> +    bio: Camilo is a software engineer specialized in real time simulation engines, 3D modeling and rendering, animations and VR technologies.
```suggestion
    bio: Camilo is a software engineer who specializes in realtime simulation engines, 3D modeling and rendering, animations and VR technologies. 
```

2023-09-12 20:09 UTC, eldu commented on about/people.yml
> +      He loves learning programing languages, and enjoys developing applications in multiple frameworks. Outside of work, he passes his time developing his own video-games,
```suggestion
      He loves learning programing languages and enjoys developing applications in multiple frameworks. Outside of work, he passes his time developing his own video games, 
```

2023-09-12 20:09 UTC, eldu commented on about/people.yml
> +      playing soccer and volunteering for multiple events accross Rhode Island.
```suggestion
      playing soccer and volunteering for multiple events across Rhode Island. 
```

2023-09-12 20:21 UTC, kmilo9999 commented
@eldu 
Applied the suggestions in your review.  Thanks you checking this PR.

2023-09-21 14:52 UTC, ashleysyg approved these changes

2023-09-21 16:02 UTC, eldu approved these changes
looks great !

2023-09-21 16:04 UTC, merged