Added most of my profile information in people.yml; Added main pictur…
brown-ccv/ccv-website-content pull request #259
Opened 2024-06-06 13:56 UTC by pneumatick

…e (waiting on hover)

Note: This branch is not currently ready to merge.
Missing information: brown_directory_uuid, hover picture

2024-06-06 14:31 UTC, galenwinsor commented
Just request someone's review when you're ready!

2024-06-06 17:18 UTC, mzhan157 approved these changes
looks good to me!

2024-06-06 19:11 UTC, eldu requested changes
Few things to change. Nice images !

2024-06-06 19:11 UTC, eldu commented on about/people.yml
> +    type: Part Time
I believe you need to add in the hyphen so it knows it's a separate entry. Right now you've overridded Melinda's entry 

```suggestion
  - name: Jose Harvey
    type: Part Time
```

2024-06-06 19:11 UTC, eldu commented on about/people.yml
> +    type: Part Time
Check out a YAML tutorial about arrays

2024-06-06 19:11 UTC, eldu commented on images/people/jose_hover.jpg
The main and hover images have different extensions `.jpg` vs `.jpeg`. Unify that and I think it'll fix the hover

2024-06-10 15:18 UTC, eldu requested changes
This looks good! Please merge main into your branch to resolve any merge conflicts

2024-06-12 16:47 UTC, eldu approved these changes
Looks good! One typo, but otherwise good to go!!

2024-06-12 16:47 UTC, eldu commented on about/people.yml
> +    bio: Jose is a data science intern in the Advanced Reseach Computing division at CCV. He is an undergraduate student at the University of Rhode Island studying Computer Science. In his spare time
typo

```suggestion
    bio: Jose is a data science intern in the Advanced Research Computing division at CCV. He is an undergraduate student at the University of Rhode Island studying Computer Science. In his spare time, he enjoys reading, playing his guitar, drawing, and exploring new places. 
```

2024-06-12 18:21 UTC, merged