Dossantos am patch 1
brown-ccv/ccv-website-content pull request #268
Opened 2024-06-10 19:06 UTC by dossantos-am

2024-06-10 19:22 UTC, eldu commented
@dossantos-am the assignee for this PR is you, can you add everyone else as reviewers? It's just above the assignee field.


Also, this PR if you take a look at the files added tab, is just an image (amazing by the way!) . Remember to push your changes to the YAML file too !

2024-06-11 13:53 UTC, eldu requested changes
Thanks for adding in your about! However, if you look at the preview link (commented in the pr), your entry is not showing up. 

Take a look at some YAML tutorials to better understand the structure. Here's one below! 
https://gettaurus.org/docs/YAMLTutorial/

Also feel free to ask other interns for help! Code buddies is a great place too!

Also please change the title of your PR to something that better describes what this PR does. 

You got this!!!

2024-06-11 13:56 UTC, eldu requested changes
okay... here I am rereviewing. the yaml looks okay i just realized your image should be renamed. Also you'll need 2 images !

2024-06-11 13:56 UTC, eldu commented on images/people/IMG_8581.jpg
Oh actually, i think you need to change this image name to `austin_main.jpg`

2024-06-11 13:59 UTC, dossantos-am commented on images/people/IMG_8581.jpg
Okay will do, I'll also get the second image in there.

2024-06-11 14:16 UTC, dossantos-am commented on images/people/IMG_8581.jpg
I'm not sure what I did after renaming the image to austin_main.jpg but the image is gone.

2024-06-11 14:32 UTC, eldu commented on images/people/IMG_8581.jpg
Can you delete and re-add the image?

2024-06-11 14:32 UTC, eldu commented on images/people/IMG_8581.jpg
I downloaded it and it doesn't work

2024-06-11 15:58 UTC, cpaniaguam reviewed
Seems to be working now 👍

2024-06-11 18:37 UTC, eldu approved these changes
Looks good! 

For future PRs, make sure to name your PRs more specifically what the PR is about.

Also take a look at conventional commits!
https://www.conventionalcommits.org/en/v1.0.0/#summary

Great job!

2024-06-11 19:03 UTC, tdivoll commented
Nice work, Austin! First PR right? Feel free to hit the Merge button now that this PR is approved.

2024-06-11 19:07 UTC, merged