new pull request to add michelange
brown-ccv/ccv-website-content pull request #273
Opened 2024-06-11 14:35 UTC by mickey0116

2024-06-11 18:52 UTC, eldu requested changes
The format of the yaml looks good and the images too! I made some comments on typos and work changes. Looks like you've replaced Jesus! So let's bring him back into the website. 

Looks good so far though !

2024-06-11 18:52 UTC, eldu commented on about/people.yml
> +  - name: Michelange Senat
Looks like you've replaced Jesus's entry with yours! You'll need to keep his entry so copy paste it back in.

2024-06-11 18:52 UTC, eldu commented on about/people.yml
> +    type: Intern
```suggestion
    type: Part Time
```

2024-06-11 18:52 UTC, eldu commented on about/people.yml
> +    bio: Michelange is a summer intern wotking with the Graphics, Software, and Data Core at CCV. She is an undergraduate student at Brown Univeristy interested in studying Applied Mathematics, Compu
typos
```suggestion
    bio: Michelange is a summer intern working with the Graphics, Software, and Data Core at CCV. She is an undergraduate student at Brown University interested in studying Applied Mathematics, Computer Science, and Economics. Outside of academics, Michelange loves matcha, hair braiding, and exploring different neighborhoods in Rhode Island. 
```

2024-06-12 20:58 UTC, mickey0116 reviewed
added Jesus back and fixed my errors

2024-06-13 13:01 UTC, broarr requested changes

2024-06-13 13:01 UTC, broarr commented on about/people.yml
> +    image: sanjana_main.jp
It looks like this might be a typo. Can you change this back to `jpg` please!

2024-06-13 13:01 UTC, broarr commented
Looks great after your revisions! One little typo and I think we're good to merge!

2024-06-13 13:02 UTC, broarr commented
You'll have to merge main in and resolve the conflicts. Let me know if you'd like help with that

2024-06-13 15:09 UTC, broarr approved these changes
Looks great, thank you! 🎉

2024-06-14 15:32 UTC, mickey0116 reviewed
done!

2024-06-14 19:41 UTC, eldu approved these changes
Amazing!!! Merge it in when you get the chance :)

2024-06-20 20:37 UTC, merged