Add elokoyi to people
brown-ccv/ccv-website-content pull request #277
Opened 2024-06-14 19:23 UTC by elokoyi1989

2024-06-14 19:38 UTC, eldu requested changes
The images in the preview aren't showing up! Love your bio!!! 

A few changes to go :)

2024-06-14 19:38 UTC, eldu commented on about/people.yml
> +    image: elizabeth_main.jpg
this image name needs to match your image filename!

2024-06-14 19:38 UTC, eldu commented on images/people/Elizabeth_hover.png
Need to convert this image to a `.jpg`

2024-06-14 19:38 UTC, eldu commented on images/people/Elizabeth_main.jpeg
Also need to convert this to a `.jpg`

2024-06-17 14:12 UTC, eldu submitted a review, later dismissed
Ah, looks like your images are still not showing up in the preview. 

In your image names, you have `Elizabeth_main.jpg` and `Elizabeth_hover.jpg`. You'll need to make that Elizabeth lowercase to match what you have in the yaml file

So close !!!

2024-06-24 16:57 UTC, elokoyi1989 reviewed
I believe I have fixed all the resuested changes fingers crossed

2024-06-25 14:55 UTC, eldu approved these changes
It looks good to me! Let's merge it in :)

2024-06-25 17:11 UTC, merged