Services: Visualization
brown-ccv/ccv-website-content pull request #67
Opened 2022-01-31 16:06 UTC by RobertGemmaJr

- Adds information about CAVE and it's current status
- Adds information about MML collaboration
- Adds links to new CAVE software (MiddleVR, Unity, Motive, etc)
- Adds list of example CAVE projects
- Removes vr.md file
- Closes issue #47

2022-01-31 17:22 UTC, RobertGemmaJr commented
Is there a way to have the `Example Projects` and `Further Reading` lists be in two columns? I think that will look better. The markdown linter doesn't like inline html though.

2022-01-31 21:35 UTC, kmilo9999 commented
Looks great !! 
It seems the link to the remote rendering documentation is broken. Also, the two first links of CAVE systems are related to the YURT, a system we no longer support.

2022-01-31 21:45 UTC, RobertGemmaJr commented
> Looks great !! It seems the link to the remote rendering documentation is broken. Also, the two first links of CAVE systems are related to the YURT, a system we no longer support.

I'll delete the old links. I think I fixed the link to Oscar too - the ID was different then I thought

2022-02-01 20:05 UTC, RobertGemmaJr commented
@mirestrepo How would I link to a different part of the website locally? I'm trying to link to the Oscar part of the website but it's not working

2022-02-02 02:12 UTC, mirestrepo requested changes
This looks great! Thanks @RobertGemmaJr!

I have few suggestions but this is pretty close!

2022-02-02 17:45 UTC, RobertGemmaJr commented
I did take this picture but it's not showing on the website. It's inside of a `<p>` tag which I imagine is what's breaking it. It takes up space with the content picture isn't actually there

![studio_4](https://user-images.githubusercontent.com/38439940/152208317-40ac3611-e502-43c7-af38-c35edb024647.jpg)

2022-02-03 21:04 UTC, mirestrepo approved these changes
Looks great!. Just accept the change in the suggested path after the other PR is merged and then we can verify that the image shows up

2022-02-03 21:04 UTC, mirestrepo commented on services/visualization/studio-4.md
> +![Studio 4](/images/studio_4.jpg)
```suggestion
![Studio 4](/content/images/studio_4.jpg)
```

New path for images coming when [this](https://github.com/brown-ccv/ccv-website-nuxt/pull/89) gets merged

2022-02-03 21:32 UTC, mirestrepo commented
🚀  The picture is there and it looks 🔥

2022-02-03 21:36 UTC, merged